# Generated by Django 2.0.6 on 2018-06-28 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sorterinput', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InsertionSortRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('char1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insertionsortrecord1', to='sorterinput.Character')),
                ('char2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insertionsortrecord2', to='sorterinput.Character')),
            ],
        ),
        migrations.CreateModel(
            name='InsertionSortController',
            fields=[
                ('controller_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='controller.Controller')),
                ('charlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorterinput.CharacterList')),
            ],
            bases=('controller.controller',),
        ),
        migrations.AddField(
            model_name='insertionsortrecord',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.InsertionSortController'),
        ),
    ]
