# Generated by Django 2.0.6 on 2018-07-12 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insertionsortcontroller',
            name='charlist',
        ),
        migrations.RemoveField(
            model_name='insertionsortcontroller',
            name='controller_ptr',
        ),
        migrations.AlterField(
            model_name='insertionsortrecord',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorterinput.CharacterList'),
        ),
        migrations.DeleteModel(
            name='Controller',
        ),
        migrations.DeleteModel(
            name='InsertionSortController',
        ),
    ]
