# Generated by Django 2.0.6 on 2018-07-17 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorterinput', '0002_characterlist_controller_type'),
        ('controller', '0002_auto_20180712_0001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsertionSortRecord',
            new_name='SortRecord',
        ),
    ]
