# Generated by Django 2.0.6 on 2018-07-17 22:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_auto_20180717_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sortrecord',
            name='char1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sortrecord1', to='sorterinput.Character'),
        ),
        migrations.AlterField(
            model_name='sortrecord',
            name='char2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sortrecord2', to='sorterinput.Character'),
        ),
    ]
