# Generated by Django 2.0.6 on 2018-07-17 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_auto_20180717_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sortrecord',
            old_name='controller',
            new_name='charlist',
        ),
    ]
