# Generated by Django 2.0.6 on 2018-08-13 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorterinput', '0002_characterlist_controller_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterImageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_link', models.TextField()),
                ('context_link', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorterinput.Character')),
            ],
        ),
        migrations.AlterField(
            model_name='characterlist',
            name='controller_type',
            field=models.CharField(choices=[('IS', 'InsertionSortController'), ('GL', 'GlickoRatingController')], default='IS', max_length=2),
        ),
    ]
