# Generated by Django 2.0.6 on 2018-08-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorterinput', '0003_auto_20180813_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterlist',
            name='show_images',
            field=models.BooleanField(default=False),
        ),
    ]
